version: '3.4'

services:
  music-manager:
    build:
      tags: [ghcr.io/ralpht42/music-manager:latest-dev]
      context: .
      target: debug
      dockerfile: ./Dockerfile
      pull: true
    container_name: music-manager-debug
    restart: unless-stopped
    entrypoint: ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=8080"] # Live Reload, kein debugpy gleichzeitig möglich
    ports:
      - 8080:8080
      - 5678:5678
    environment:
      - FLASK_DEBUG=1 # Aktiviert den Debug-Modus von Flask
    env_file:
      - ./.env
    volumes:
      - .:/app # Wenn das Arbeitsverzeichnis in /app gesetzt wird, kann hot-reload verwendet werden