version: "3.4"

services:
  music-manager:
    #    image: ghcr.io/ralpht42/music-manager:latest # Entkommentieren und die build-Zeilen entfernen, wenn das Image nicht selbst gebaut werden soll
    build:
      tags: [ghcr.io/ralpht42/music-manager:latest-dev]
      context: .
      target: production
      dockerfile: ./Dockerfile
      pull: true
    container_name: music-manager
    restart: unless-stopped
    volumes:
      - ./data:/opt/music-manager/data
    #    environment: # Entkommentieren, wenn keine .env-Datei vorhanden ist und die Werte hier eingetragen werden sollen
    #      - SECRET_KEY=1234567890
    env_file:
      - ./.env
    ports:
      - 8080:8080
