version: '3.4'

services:
  musicmanager:
    image: musicmanager:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: musicmanager
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      # Zuf채llige Zeichenkette, die als Schl체ssel f체r die Verschl체sselung verwendet wird
      - SECRET_KEY=FgbPnKD7xi@Gq&MpVbf43y6Zb7Mibo 
    ports:
      - 8080:8080
