name: Create new Release
on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  Release:
    if: ${{ !contains(github.event.head_commit.message, 'chore(release):') }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN_PAT }}
      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@67971bf454b8ac56345cc51e939a00aa391d9117 # v8.1.2
        with:
          github_token: ${{ secrets.GH_TOKEN_PAT }}
          git_committer_name: "github-actions[bot]"
          git_committer_email: "41898282+github-actions[bot]@users.noreply.github.com"
