name: Create new Release
on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  Release:
    if: ${{ !contains(github.event.head_commit.message, 'chore(release):') }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN_PAT }}
      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@02fa4d21a2f06f31a8088508c6eacb57ee08f1b8 # v8.1.2
        with:
          github_token: ${{ secrets.GH_TOKEN_PAT }}
          git_committer_name: "github-actions[bot]"
          git_committer_email: "41898282+github-actions[bot]@users.noreply.github.com"
