name: Create new Release
on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  Release:
    if: ${{ !contains(github.event.head_commit.message, 'chore(release):') }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN_PAT }}
      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@e34d7bdb9bb9a7e00c1f74f3d7313e9a3b5a12f4 # v8.1.2
        with:
          github_token: ${{ secrets.GH_TOKEN_PAT }}
          git_committer_name: "github-actions[bot]"
          git_committer_email: "41898282+github-actions[bot]@users.noreply.github.com"
